spring:
    jpa:
      hibernate:
       ddl-auto: update
      properties:
         dialect: org.hibernate.dialect.MySQL5Dialect
    datasource:
        url: jdbc:mysql://localhost:3306
        username: root
        password: Intruder54+
        driver-class-name: com.mysql.cj.jdbc.Driver